name: Commit Message Lint (Jira)

on:
  pull_request:
    branches:
        - develop
    types: [opened, edited, synchronize, reopened]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install commitlint
        run: |
          npm install --save-dev @commitlint/{config-conventional,cli}

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.js
