name: Sync Shopify Theme Updates

on:
  push:
    branches:
      - shopify-live

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print commit message
        run: echo "Commit message:${{ github.event.head_commit.message }}"

  sync-branches:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Shopify')
    steps:
      - name: Checkout shopify-live
        uses: actions/checkout@v3
        with:
          ref: shopify-live
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config user.name "Shopify Sync Bot"
          git config user.email "sync-bot@example.com"

      - name: Merge into develop
        run: |
          git checkout develop
          git merge -X theirs shopify-live --no-edit || true
          git push origin develop


      - name: Create merge branch from shopify-live
        run: |
          git checkout -b merge-shopify-live
          git fetch origin main
          git merge origin/main --no-edit || true

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Create pull request to main
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync from Shopify live"
          title: "Merge updates from Shopify live"
          body: "Cette PR contient les changements poussés depuis Shopify (branche `shopify-live`)."
          base: main
          branch: merge-shopify-live

      - name: Auto-merge the PR
        if: steps.cpr.outputs.pull-request-number != ''
        run: gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --merge --admin --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
