name: Sync Shopify Theme Updates

on:
  push:
    branches:
      - shopify-live

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print commit message
        run: echo "Commit message:${{ github.event.head_commit.message }}"

  sync-branches:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Shopify')
    steps:
      - name: Checkout shopify-live
        uses: actions/checkout@v3
        with:
          ref: shopify-live
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config user.name "Shopify Sync Bot"
          git config user.email "sync-bot@example.com"

      - name: Merge into develop
        run: |
          git checkout develop
          git merge -X theirs shopify-live --no-edit || true
          git push origin develop


      - name: Merge into main
        run: |
          git checkout main
          git merge -X theirs shopify-live --no-edit || true
          git push origin main
